-- ==========================================
-- DML: POPULATING ADVANCED HR SCHEMA
-- ==========================================

-- DEPARTMENTS
INSERT INTO departments (dept_id, dept_name) VALUES (1, 'Executive');
INSERT INTO departments (dept_id, dept_name) VALUES (2, 'IT');
INSERT INTO departments (dept_id, dept_name) VALUES (3, 'Finance');
INSERT INTO departments (dept_id, dept_name) VALUES (4, 'HR');
INSERT INTO departments (dept_id, dept_name) VALUES (5, 'Operations');

-- MANAGERS (Top Level)
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (1, 'Ali Khan', 'manager1@company.com', 93171, NULL, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (2, 'Fatima Iqbal', 'manager2@company.com', 113893, NULL, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (3, 'Ali Ahmed', 'manager3@company.com', 102598, NULL, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (4, 'Bilal Malik', 'manager4@company.com', 121914, NULL, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (5, 'John Khan', 'manager5@company.com', 103525, NULL, 5);

-- REGULAR EMPLOYEES
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (6, 'Bilal Iqbal', 'emp6@company.com', 56275, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (7, 'Bilal Iqbal', 'emp7@company.com', 56389, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (8, 'Fatima Smith', 'emp8@company.com', 42885, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (9, 'Fatima Shah', 'emp9@company.com', 58965, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (10, 'Zahra Shah', 'emp10@company.com', 78829, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (11, 'Ali Ali', 'emp11@company.com', 80781, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (12, 'Aisha Ali', 'emp12@company.com', 63717, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (13, 'Omar Jones', 'emp13@company.com', 63509, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (14, 'Aisha Ahmed', 'emp14@company.com', 76150, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (15, 'Fatima Iqbal', 'emp15@company.com', 56319, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (16, 'Omar Khan', 'emp16@company.com', 66101, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (17, 'Bilal Malik', 'emp17@company.com', 82341, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (18, 'Omar Malik', 'emp18@company.com', 41908, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (19, 'Ali Jones', 'emp19@company.com', 48247, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (20, 'Aisha Khan', 'emp20@company.com', 48106, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (21, 'Zahra Ahmed', 'emp21@company.com', 61285, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (22, 'Aisha Ali', 'emp22@company.com', 47152, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (23, 'Zahra Iqbal', 'emp23@company.com', 49593, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (24, 'Michael Smith', 'emp24@company.com', 76833, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (25, 'Ali Khan', 'emp25@company.com', 81577, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (26, 'Fatima Smith', 'emp26@company.com', 79938, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (27, 'John Ali', 'emp27@company.com', 48718, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (28, 'Emma Ali', 'emp28@company.com', 52878, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (29, 'John Khan', 'emp29@company.com', 59522, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (30, 'John Ali', 'emp30@company.com', 83142, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (31, 'John Ahmed', 'emp31@company.com', 46422, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (32, 'Omar Shah', 'emp32@company.com', 49440, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (33, 'Zahra Jones', 'emp33@company.com', 56420, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (34, 'Emma Ahmed', 'emp34@company.com', 49866, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (35, 'John Ahmed', 'emp35@company.com', 59357, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (36, 'Fatima Malik', 'emp36@company.com', 54532, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (37, 'Omar Malik', 'emp37@company.com', 75924, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (38, 'John Iqbal', 'emp38@company.com', 65590, 3, 3);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (39, 'John Malik', 'emp39@company.com', 57561, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (40, 'Bilal Smith', 'emp40@company.com', 80865, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (41, 'Sara Jones', 'emp41@company.com', 55333, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (42, 'John Iqbal', 'emp42@company.com', 72117, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (43, 'John Jones', 'emp43@company.com', 61247, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (44, 'Bilal Smith', 'emp44@company.com', 76847, 2, 2);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (45, 'Fatima Khan', 'emp45@company.com', 79656, 1, 1);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (46, 'Ali Smith', 'emp46@company.com', 84870, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (47, 'Sara Jones', 'emp47@company.com', 57458, 4, 4);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (48, 'Sara Ali', 'emp48@company.com', 46499, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (49, 'John Ahmed', 'emp49@company.com', 49319, 5, 5);
INSERT INTO employees (emp_id, emp_name, email, salary, manager_id, dept_id) VALUES (50, 'Michael Ali', 'emp50@company.com', 78865, 5, 5);

-- PROJECTS
INSERT INTO projects (project_id, project_name, budget) VALUES (1, 'Cloud Migration', 61116);
INSERT INTO projects (project_id, project_name, budget) VALUES (2, 'Q3 Audit', 88869);
INSERT INTO projects (project_id, project_name, budget) VALUES (3, 'New App Launch', 61153);
INSERT INTO projects (project_id, project_name, budget) VALUES (4, 'Office Move', 99684);
INSERT INTO projects (project_id, project_name, budget) VALUES (5, 'Security Patch', 52422);

-- ASSIGNMENTS
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (1, 17, 1, 86);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (2, 45, 4, 90);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (3, 39, 2, 61);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (4, 42, 4, 84);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (5, 47, 4, 86);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (6, 7, 4, 116);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (7, 7, 1, 56);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (8, 19, 2, 28);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (9, 25, 1, 66);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (10, 16, 2, 7);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (11, 16, 3, 75);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (12, 29, 2, 120);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (13, 4, 4, 67);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (14, 37, 5, 58);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (15, 26, 2, 5);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (16, 39, 5, 120);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (17, 38, 4, 75);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (18, 38, 3, 44);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (19, 35, 1, 96);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (20, 40, 3, 76);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (21, 42, 5, 77);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (22, 3, 1, 60);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (23, 3, 1, 40);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (24, 2, 2, 76);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (25, 17, 5, 119);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (26, 42, 2, 7);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (27, 6, 5, 42);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (28, 4, 2, 82);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (29, 42, 2, 39);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (30, 18, 1, 25);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (31, 50, 4, 108);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (32, 25, 1, 27);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (33, 14, 1, 30);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (34, 1, 1, 29);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (35, 16, 2, 102);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (36, 46, 1, 98);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (37, 3, 1, 59);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (38, 32, 2, 38);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (39, 27, 4, 83);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (40, 38, 4, 98);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (41, 43, 3, 82);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (42, 44, 4, 64);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (43, 32, 1, 64);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (44, 3, 4, 59);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (45, 5, 3, 33);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (46, 29, 3, 119);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (47, 44, 1, 7);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (48, 11, 2, 84);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (49, 32, 2, 53);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (50, 2, 5, 88);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (51, 21, 1, 63);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (52, 26, 3, 113);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (53, 37, 5, 74);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (54, 49, 1, 21);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (55, 32, 1, 114);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (56, 28, 5, 95);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (57, 11, 5, 85);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (58, 32, 5, 116);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (59, 4, 2, 11);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (60, 48, 4, 58);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (61, 24, 1, 72);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (62, 22, 3, 98);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (63, 14, 4, 111);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (64, 47, 5, 52);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (65, 13, 4, 40);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (66, 11, 5, 50);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (67, 9, 5, 25);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (68, 37, 3, 107);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (69, 24, 2, 99);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (70, 36, 4, 61);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (71, 28, 3, 84);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (72, 20, 1, 65);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (73, 38, 3, 63);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (74, 24, 3, 10);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (75, 25, 5, 109);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (76, 49, 2, 45);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (77, 9, 4, 118);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (78, 46, 3, 103);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (79, 42, 4, 107);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (80, 35, 3, 44);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (81, 47, 4, 21);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (82, 9, 4, 13);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (83, 21, 3, 5);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (84, 16, 4, 74);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (85, 21, 4, 115);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (86, 47, 4, 81);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (87, 11, 1, 15);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (88, 13, 4, 109);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (89, 17, 4, 30);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (90, 21, 5, 16);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (91, 31, 4, 117);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (92, 37, 5, 73);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (93, 32, 2, 20);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (94, 47, 1, 90);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (95, 31, 4, 65);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (96, 5, 5, 7);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (97, 19, 3, 33);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (98, 17, 4, 31);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (99, 45, 4, 15);
INSERT INTO assignments (assign_id, emp_id, project_id, hours_logged) VALUES (100, 13, 4, 103);

COMMIT;
